name: Update README Version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get release version
      id: get_version
      run: echo "KEY=version::$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >>$GITHUB_OUTPUT

    - name: Update README.md
      run: |
        sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/v${{ steps.get_version.outputs.version }}/g" README.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout master
        git add README.md
        git commit -m "Update README version to ${{ steps.get_version.outputs.version }}."
        git push origin master
